############################################################################
# vendor/rockchip/boards/rk3506/luckfox-lyra-zero-w/src/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(TOPDIR)/Make.defs

CSRCS = luckfox_boardinit.c luckfox_gpio.c luckfox_sdmmc.c

include $(TOPDIR)/boards/Board.mk
