############################################################################
# apps/system/a733wifi/Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_A733WIFI_PROGNAME)
PRIORITY  = $(CONFIG_A733WIFI_PRIORITY)
STACKSIZE = $(CONFIG_A733WIFI_STACKSIZE)
MODULE    = $(CONFIG_SYSTEM_A733WIFI)
MAINSRC   = a733wifi_main.c

include $(APPDIR)/Application.mk
