include $(APPDIR)/Make.defs
PROGNAME = service
PRIORITY = 100
STACKSIZE = 8192
MODULE = $(CONFIG_SYSTEM_A733SERVICES)
MAINSRC = a733services_main.c
CSRCS = services_config.c
include $(APPDIR)/Application.mk
