############################################################################
# vendor/rockchip/boards/rv1103/luckfox-pico-mini/src/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(TOPDIR)/Make.defs

CSRCS = luckfox_boardinit.c luckfox_gpio.c luckfox_peripherals.c
CSRCS += luckfox_sdmmc.c

include $(TOPDIR)/boards/Board.mk
